version: "3"

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./api
    ports:
      - "7000:7000"
    environment:
      NODE_ENV: development
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecretpassword
      MYSQL_DATABASE: test_pill
    depends_on:
      - mysql
    volumes:
      - ./api:/app

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: test_pill
    ports:
      - "3306:3306"
